<a href="https://colab.research.google.com/github/yayie77/Concepts-and-Technologies-of-AI/blob/main/7_Workshop_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import sklearn

# Display version information for scikit-learn
sklearn.show_versions()


System:
    python: 3.12.0 (tags/v3.12.0:0fb18b0, Oct  2 2023, 13:03:39) [MSC v.1935 64 bit (AMD64)]
executable: C:\Users\HP\AppData\Local\Programs\Python\Python312\python.exe
   machine: Windows-11-10.0.26100-SP0

Python dependencies:
      sklearn: 1.5.2
          pip: 24.3.1
   setuptools: None
        numpy: 1.26.4
        scipy: 1.13.0
       Cython: None
       pandas: 2.2.3
   matplotlib: 3.8.3
       joblib: 1.4.2
threadpoolctl: 3.5.0

Built with OpenMP: True

threadpoolctl info:
       user_api: openmp
   internal_api: openmp
    num_threads: 12
         prefix: vcomp
       filepath: C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\.libs\vcomp140.dll
        version: None

       user_api: blas
   internal_api: openblas
    num_threads: 12
         prefix: libopenblas
       filepath: C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy.libs\libopenblas64__v0.3.23-293-gc2f4bdbb-gcc_10_3_0-2bde3a66a51006b2b53eb373ff767a3f.dl

Feature Matrix - X
Target Vector (y)

Limiting Classes (n class)

Data Pre-processing with scikit learn

In [ ]:
from sklearn.preprocessing import StandardScaler

# Example data
data = [[0, 0], [0, 0], [1, 1], [1, 1]]

# Initialize the transformer
scaler = StandardScaler()

# Step 1: Fit to the data (compute mean and std)
scaler.fit(data)

# Step 2: Transform the data
transformed_data = scaler.transform(data)

# Step 3: Alternatively, use fit_transform to do both steps at once
transformed_data_direct = scaler.fit_transform(data)

# Print results
print("Transformed Data (using fit and transform):")
print(transformed_data)

print("\nTransformed Data (using fit_transform):")
print(transformed_data_direct)

Transformed Data (using fit and transform):
[[-1. -1.]
 [-1. -1.]
 [ 1.  1.]
 [ 1.  1.]]

Transformed Data (using fit_transform):
[[-1. -1.]
 [-1. -1.]
 [ 1.  1.]
 [ 1.  1.]]


In [ ]:
from sklearn.model_selection import train_test_split

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.25,  # Proportion of data to use for testing (between 0 and 1)
    train_size=None,  # Optional, can specify training size if test_size is None
    random_state=None,  # Seed for reproducibility of random splits
    shuffle=True,  # Shuffle the data before splitting
    stratify=None  # Ensures similar class distribution in train/test (for classification)
)

In [ ]:
from sklearn.model_selection import train_test_split
import numpy as np

# Example dataset
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
y = np.array([0, 1, 0, 1, 0])

# Split the dataset (80% training, 20% testing)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Print the splits
print("X_train:", X_train)
print("X_test:", X_test)
print("y_train:", y_train)
print("y_test:", y_test)


X_train: [[ 9 10]
 [ 5  6]
 [ 1  2]
 [ 7  8]]
X_test: [[3 4]]
y_train: [0 0 0 1]
y_test: [1]


Estimators in scikit learn

In [ ]:
class Estimator(object):
    def fit(self, X, y=None):
        """
        Fits the estimator to data.
        Stores the input data and target labels to simulate learning.
        """
        # Store the data to simulate learning
        self.X_ = X
        self.y_ = y
        return self

    def predict(self, X):
        """
        Makes predictions using the learned data.
        For this simple example, it returns the stored labels.
        In a real scenario, this would apply a trained model to the new data.
        """
        # Check if the model has been fitted
        if not hasattr(self, "X_"):
            raise ValueError("Model has not been fitted yet.")

        # Return the stored labels as predictions (for demonstration purposes)
        return self.y_

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

# Load Iris dataset
iris = load_iris()
X, y = iris.data, iris.target

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Set hyperparameters for the KNeighborsClassifier
clf = KNeighborsClassifier(n_neighbors=5)

# Train the model using the training data
clf.fit(X_train, y_train)

# Make predictions on the first 5 samples from X_test
print("Predictions for the first 5 samples:", clf.predict(X_test[:5]))

# Compute class probabilities for the first 5 samples
print("Class probabilities for the first 5 samples:", clf.predict_proba(X_test[:5]))

Predictions for the first 5 samples: [1 0 2 1 1]
Class probabilities for the first 5 samples: [[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]]


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

# Load Iris dataset
iris = load_iris()
X, y = iris.data, iris.target

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Set hyperparameters for the KNeighborsClassifier
clf = KNeighborsClassifier(n_neighbors=5)

# Train the model using the training data
clf.fit(X_train, y_train)

# Make predictions on the first 5 samples from X_test
print("Predictions for the first 5 samples:", clf.predict(X_test[:5]))

# Compute class probabilities for the first 5 samples
print("Class probabilities for the first 5 samples:", clf.predict_proba(X_test[:5]))

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

# Example dataset (assuming X and y are already defined)
# Replace with your actual dataset if needed
# X: Feature matrix, y: Target vector

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Set hyperparameters for the KNeighborsClassifier
clf = KNeighborsClassifier(n_neighbors=5)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

# Assuming X and y are defined earlier in your code (e.g., dataset features and target)

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Set hyperparameters for the KNeighborsClassifier
clf = KNeighborsClassifier(n_neighbors=5)

# Train the model using the training data
clf.fit(X_train, y_train)

KNeighborsClassifier()

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris

# Load the Iris dataset as an example
iris = load_iris()
X, y = iris.data, iris.target

# Split data into training and testing sets (80% training, 20% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Set hyperparameters for the KNeighborsClassifier
clf = KNeighborsClassifier(n_neighbors=5)

# Train the model using the training data
clf.fit(X_train, y_train)

# Make predictions using the test data
predictions = clf.predict(X_test)
print("Predictions:", predictions)

# Compute class probabilities for the test data
probabilities = clf.predict_proba(X_test)
print("Class probabilities for the test data:", probabilities)

Predictions: [1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0 0 0 2 1 1 0 0]
Class probabilities for the test data: [[0.  1.  0. ]
 [1.  0.  0. ]
 [0.  0.  1. ]
 [0.  1.  0. ]
 [0.  1.  0. ]
 [1.  0.  0. ]
 [0.  1.  0. ]
 [0.  0.  1. ]
 [0.  0.6 0.4]
 [0.  1.  0. ]
 [0.  0.2 0.8]
 [1.  0.  0. ]
 [1.  0.  0. ]
 [1.  0.  0. ]
 [1.  0.  0. ]
 [0.  0.8 0.2]
 [0.  0.  1. ]
 [0.  1.  0. ]
 [0.  1.  0. ]
 [0.  0.  1. ]
 [1.  0.  0. ]
 [0.  0.2 0.8]
 [1.  0.  0. ]
 [0.  0.  1. ]
 [0.  0.  1. ]
 [0.  0.  1. ]
 [0.  0.  1. ]
 [0.  0.  1. ]
 [1.  0.  0. ]
 [1.  0.  0. ]
 [1.  0.  0. ]
 [1.  0.  0. ]
 [0.  1.  0. ]
 [1.  0.  0. ]
 [1.  0.  0. ]
 [0.  0.4 0.6]
 [0.  1.  0. ]
 [1.  0.  0. ]
 [1.  0.  0. ]
 [1.  0.  0. ]
 [0.  0.2 0.8]
 [0.  0.8 0.2]
 [0.  1.  0. ]
 [1.  0.  0. ]
 [1.  0.  0. ]]


In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Example for regression
y_true_regression = [3, -0.5, 2, 7]
y_pred_regression = [2.5, 0.0, 2, 8]

# Calculate MAE, MSE, and R2
mae = mean_absolute_error(y_true_regression, y_pred_regression)
mse = mean_squared_error(y_true_regression, y_pred_regression)
r2 = r2_score(y_true_regression, y_pred_regression)

# Print the results
print(f"MAE: {mae}, MSE: {mse}, R2: {r2}")

MAE: 0.5, MSE: 0.375, R2: 0.9486081370449679


In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

# Example for classification
y_true_classification = [0, 1, 1, 0, 1]
y_pred_classification = [0, 1, 0, 0, 1]

# Calculate Accuracy, Precision, Recall, F1 score, and ROC AUC score
accuracy = accuracy_score(y_true_classification, y_pred_classification)
precision = precision_score(y_true_classification, y_pred_classification)
recall = recall_score(y_true_classification, y_pred_classification)
f1 = f1_score(y_true_classification, y_pred_classification)
roc_auc = roc_auc_score(y_true_classification, y_pred_classification)

# Print the results
print(f"Accuracy: {accuracy}, Precision: {precision}, Recall: {recall}, F1-Score: {f1}, ROC AUC: {roc_auc}")


Accuracy: 0.8, Precision: 1.0, Recall: 0.6666666666666666, F1-Score: 0.8, ROC AUC: 0.8333333333333333
